export const WARRANTY_REQUEST_STATUS_PENDING = '접수 대기'
export const WARRANTY_REQUEST_STATUS_IN_PROGRESS = '작성 중'
export const WARRANTY_REQUEST_STATUS_COMPLETED = '발행 완료'

export const WARRANTY_REQUEST_STATUSES = [
  WARRANTY_REQUEST_STATUS_PENDING,
  WARRANTY_REQUEST_STATUS_IN_PROGRESS,
  WARRANTY_REQUEST_STATUS_COMPLETED,
] as const

export type WarrantyRequestStatus = (typeof WARRANTY_REQUEST_STATUSES)[number]
